// AUTO-GENERATED FILE. DO NOT EDIT.
import type { LanguageId } from "../language-ids";
import type { CoreConcept } from "./core-concepts";

export type ConceptCoverage = {
  confidence: number;
  limitations: string[];
};

export const COVERAGE_MATRIX: Record<LanguageId, Record<CoreConcept, ConceptCoverage>> = {
  "ansible": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill ansible"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill ansible"] }
  },
  "assembly": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill assembly"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill assembly"] }
  },
  "awk": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill awk"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill awk"] }
  },
  "bash": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill bash"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill bash"] }
  },
  "c": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill c"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill c"] }
  },
  "clojure": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill clojure"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill clojure"] }
  },
  "coffeescript": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill coffeescript"] }
  },
  "cpp": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill cpp"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill cpp"] }
  },
  "crystal": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill crystal"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill crystal"] }
  },
  "csharp": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill csharp"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill csharp"] }
  },
  "css": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill css"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill css"] }
  },
  "dart": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill dart"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill dart"] }
  },
  "dockerfile": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill dockerfile"] }
  },
  "elixir": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill elixir"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill elixir"] }
  },
  "erlang": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill erlang"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill erlang"] }
  },
  "fortran": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill fortran"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill fortran"] }
  },
  "fsharp": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill fsharp"] }
  },
  "go": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill go"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill go"] }
  },
  "graphql": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill graphql"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill graphql"] }
  },
  "groovy": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill groovy"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill groovy"] }
  },
  "haskell": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill haskell"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill haskell"] }
  },
  "html": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill html"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill html"] }
  },
  "java": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill java"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill java"] }
  },
  "javascript": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill javascript"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill javascript"] }
  },
  "json": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill json"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill json"] }
  },
  "julia": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill julia"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill julia"] }
  },
  "kotlin": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill kotlin"] }
  },
  "lua": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill lua"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill lua"] }
  },
  "markdown": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill markdown"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill markdown"] }
  },
  "matlab": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill matlab"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill matlab"] }
  },
  "nim": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill nim"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill nim"] }
  },
  "objective-c": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill objective-c"] }
  },
  "ocaml": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill ocaml"] }
  },
  "perl": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill perl"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill perl"] }
  },
  "php": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill php"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill php"] }
  },
  "powershell": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill powershell"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill powershell"] }
  },
  "python": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill python"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill python"] }
  },
  "r": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill r"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill r"] }
  },
  "ruby": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill ruby"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill ruby"] }
  },
  "rust": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill rust"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill rust"] }
  },
  "sas": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill sas"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill sas"] }
  },
  "sed": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill sed"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill sed"] }
  },
  "scala": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill scala"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill scala"] }
  },
  "solidity": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill solidity"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill solidity"] }
  },
  "sql": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill sql"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill sql"] }
  },
  "swift": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill swift"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill swift"] }
  },
  "terraform": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill terraform"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill terraform"] }
  },
  "typescript": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill typescript"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill typescript"] }
  },
  "vbnet": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill vbnet"] }
  },
  "xml": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill xml"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill xml"] }
  },
  "yaml": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill yaml"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill yaml"] }
  },
  "zig": {
      "generics": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "iterators": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "closures": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "pattern-matching": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "concurrency": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "error-handling": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "memory-management": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "object-oriented": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "functional": { confidence: 0.5, limitations: ["TODO: Fill zig"] },
      "metaprogramming": { confidence: 0.5, limitations: ["TODO: Fill zig"] }
  }
};
